apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logingress
  namespace: logoutput
  labels:
    name: logingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/pingpong"
        backend:
          service:
            name: pingpong-svc
            port: 
              number: 5563
      - pathType: Prefix
        path: "/logoutput"
        backend:
          service:
            name: logoutput-svc
            port: 
              number: 4563
      - pathType: Prefix
        path: /images
        backend:
          service:
            name: images-svc
            port: 
              number: 2346
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projingress
  namespace: project
  labels:
    name: projingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/graphql"
        backend:
          service:
            name: k8sproj-svc 
            port: 
              number: 2345   # This is a port that is specified in service
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: k8sfrontend-svc
            port: 
              number: 3000   # This is a port that is specified in service