_default:
  @just --list

# Build a new docker image 
build:
    ./build-push.sh

cleanup:
    docker -n mooc delete -f manifests/deployment.yaml 
test:
    docker run -it --name mooc rsarpal/k8s_k8sfrontend