apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- manifest/deployment.yaml
- manifest/service_clusterip.yaml
images:
- name: PROJECT/IMAGE
  newName: rsarpal/k8s_k8sfrontend