# https://hub.docker.com/_/python
FROM python:3.7-slim

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y sqlite3

# Copy local code to the container image.
RUN mkdir /usr/k8sproj
WORKDIR /usr/k8sproj


COPY . /usr/k8sproj/

RUN pip3 install -r requirements.txt

# expose port 8000 for Django
EXPOSE 8000

# set FLASK env variables
#ENV FLASK_APP=app.py
#ENV FLASK_RUN_PORT=8080

# setup entrypoint
RUN chmod +x /usr/k8sproj/startup.sh
ENTRYPOINT ["/usr/k8sproj/startup.sh"]
