apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- manifests/deployment.yaml
- manifests/gcloud_service.yaml
images:
- name: PROJECT/IMAGE
  newName: rsarpal/k8s_k8sproj