# https://hub.docker.com/_/python
FROM python:3.7-slim

# install pdfkit dependency - html to pdf converter https://wkhtmltopdf.org
RUN apt-get update \
  && apt-get upgrade -y

RUN pip3 install flask flask_sqlalchemy psycopg2-binary
  

# Copy local code to the container image.
RUN mkdir /usr/pingpong
WORKDIR /usr/pingpong

COPY . /usr/pingpong/

# expose port 5000 for gcloud
EXPOSE 5000

# set FLASK env variables
ENV FLASK_APP=pingpong.py
ENV FLASK_RUN_PORT=5000


RUN chmod +x /usr/pingpong/startup.sh
ENTRYPOINT ["/usr/pingpong/startup.sh"]