_default:
  @just --list

# Build a new docker image 
build:
    ./build-push.sh


cleanup:
    kubectl -n mooc delete -f manifests/deployment.yaml 
    kubectl delete --all pods --namespace=mooc

test:
    docker run --rm -p 5000:5000 -it --name mooc rsarpal/pingpong