apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sproj-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sproj
  template:
    metadata:
      labels:
        app: k8sproj
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
      - name: k8sproj
        image: rsarpal/k8s_k8sproj
        volumeMounts:
          - name: shared-image
            mountPath: /tmp/kube
        resources:
          limits:
            memory: "100Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
           name: postgres-secret
        - configMapRef:
           name: postgres-configmap
        # readinessProbe:
        #   periodSeconds: 5
        #   successThreshold: 1
        #   httpGet:
        #     path: /admin
        #     port: 8000
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: kubernetes.io/hostname
      #               operator: In
      #               values: ["k3d-k3s-default-agent-0"]

